### ISSUE TITLE
Qual IDE a ser utilizada para desenvolvimento do sistema módulo empresa.

### ISSUE THREAD

**Issue by Lucianocljr** [Lucianocljr/TCC-4Periodo-IFPE-Campus-Garanhuns#1]
Vocês preferem qual IDE?
1 - NetBeans;
2 - Eclipse.
@MarcelaCCM, @felipellins.

**Comment by felipellins** [comment]
2 - Eclipse.

Em seg, 18 de fev de 2019 20:21, Lucianocljr <notifications@github.com
escreveu:

**Comment by Lucianocljr** [comment]
Ok, então vai ser o eclipse mesmo.
